controllers:
    resource: ../src/Controller/
    type: attribute
kernel:
    resource: ../src/Kernel.php
    type: attribute

app_logout:
    path: /logout
    methods: GET

user_list:
    path: /users
    controller: App\Controller\UserController::index

user_show:
    path: /users/{id}
    controller: App\Controller\UserController::show
    methods:    GET

user_delete:
    path: /users/{id}
    controller: App\Controller\UserController::delete
    methods:   DELETE|POST

categories_list:
    path: /categories
    controller: App\Controller\CategoryController::index

categories_show:
    path: /categories/{id}
    controller: App\Controller\CategoryController::show
    methods:    GET

categories_create_form:
    path: /categories_create
    controller: App\Controller\CategoryController::create
    methods:    GET

categories_create:
    path: /store_categories
    controller: App\Controller\CategoryController::store
    methods:    POST

categories_update:
    path: /update_categories/{id}
    controller: App\Controller\CategoryController::update
    methods:    PUT|POST

categories_delete:
    path: /categories/{id}
    controller: App\Controller\CategoryController::delete
    methods:    DELETE|POST

movie_list:
    path: /movies
    controller: App\Controller\MovieController::index

movie_show:
    path: /movies/{id}
    controller: App\Controller\MovieController::show
    methods:    GET

movie_create_form:
    path: /movies_create
    controller: App\Controller\MovieController::create
    methods:    GET

movie_create:
    path: /store_movies
    controller: App\Controller\MovieController::store
    methods:    POST

movie_update:
    path: /update_movies/{id}
    controller: App\Controller\MovieController::update
    methods:    PUT|POST

movie_delete:
    path: /movies/{id}
    controller: App\Controller\MovieController::delete
    methods:    DELETE|POST

actor_list:
    path: /actors
    controller: App\Controller\ActorController::index

actor_show:
    path: /actors/{id}
    controller: App\Controller\ActorController::show
    methods:    GET

actor_create_form:
    path: /actors_create
    controller: App\Controller\ActorController::create
    methods:    GET

actor_create:
    path: /store_actors
    controller: App\Controller\ActorController::store
    methods:    POST

actor_update:
    path: /update_actors/{id}
    controller: App\Controller\ActorController::update
    methods:    PUT|POST

actor_delete:
    path: /actors/{id}
    controller: App\Controller\ActorController::delete
    methods:    DELETE|POST

redis_test:
    path: /redis-test
    controller: App\Controller\TestController::test

comment_create:
    path: /comment-create/{id}
    controller: App\Controller\CommentController::store
    methods:    POST

search_movies:
    path: /search-movies
    controller: App\Controller\ApiSearchMoviesController::index
    methods: GET

search_by_title:
    path: /search-by-title
    controller: App\Controller\ApiSearchMoviesController::searchByTitle
    methods: GET

show_by_imdb_id:
    path: /show-by-imdb/{imdb_id}
    controller: App\Controller\ApiSearchMoviesController::showByImdbId
    methods: GET